In [92]:
# Pandas kitabxanasını `pd` qısa adı ilə import edirik.
import pandas as pd  # pip install pandas

# NumPy kitabxanasını `np` qısa adı ilə import edirik.
import numpy as np  # pip install numpy

**Pandas** - CSV, Excel, SQL Cədvəllərlə və s. data topluları ilə işlmək üçün kitabxana

In [93]:
# `help()` verilmiş obyekt haqqında Python-un daxili kömək məlumatını göstərir.
# Burada `pd.Series` sinfi haqqında dokumentasiyanı göstərmək üçün istifadə oluna bilər.
# help(pd.Series)

In [94]:
# Series üçün istifadə olunacaq indeks adlarını siyahı şəklində yaradırıq.
my_index = ['USA', 'Canada', 'Mexico', "Azerbaijan"]

In [95]:
# Series daxilində saxlanılacaq dəyərləri siyahı şəklində yaradırıq.
my_data = [1776, 1867, 1821, 1944]

In [96]:
# `pd.Series()` birölçülü etiketlənmiş məlumat strukturu yaradır.
# `data=my_data` — saxlanılacaq dəyərlərdir.
# `index=my_index` — hər dəyər üçün istifadə olunacaq indeks adlarıdır.
my_series = pd.Series(data=my_data, index=my_index)

In [97]:
# `my_series` obyektini ekrana çıxarırıq.
my_series

USA           1776
Canada        1867
Mexico        1821
Azerbaijan    1944
dtype: int64

In [98]:
# `"Azerbaijan"` indeksinə uyğun olan dəyəri Series-dən seçirik.
my_series["Azerbaijan"]

np.int64(1944)

In [99]:
# Açar-dəyər cütlərindən ibarət dictionary yaradırıq.
ages = {"Sam": 5, "Frank": 10, "Spike": 7, "Nadir": 45}

In [100]:
# Dictionary-dən Series yaradırıq.
# Dictionary açarları indeks, dəyərləri isə Series-in dəyərləri olur.
pd.Series(ages)

Sam       5
Frank    10
Spike     7
Nadir    45
dtype: int64

In [101]:
# Birinci rüb üçün ölkələr üzrə satış məlumatlarını dictionary şəklində yaradırıq.
q1 = {'Japan': 80, 'China': 450, 'India': 200, 'USA': 250}

# İkinci rüb üçün ölkələr üzrə satış məlumatlarını dictionary şəklində yaradırıq.
q2 = {'Brazil': 100, 'China': 500, 'India': 2, 'USA': 260}

In [102]:
# `q1` dictionary-sindən Series yaradırıq.
sales_q1 = pd.Series(q1)

# `q2` dictionary-sindən Series yaradırıq.
sales_q2 = pd.Series(q2)

In [103]:
# Birinci rüb satış Series-ini göstəririk.
sales_q1

Japan     80
China    450
India    200
USA      250
dtype: int64

In [104]:
# İkinci rüb satış Series-ini göstəririk.
sales_q2

Brazil    100
China     500
India       2
USA       260
dtype: int64

In [105]:
# `.keys()` Series-in indekslərini qaytarır.
sales_q1.keys()

Index(['Japan', 'China', 'India', 'USA'], dtype='str')

In [106]:
# Series-dəki bütün ədədi dəyərləri 2-yə vururuq.
# Əməliyyat hər element üçün ayrıca tətbiq olunur.
sales_q1 * 2

Japan    160
China    900
India    400
USA      500
dtype: int64

In [107]:
# İki Series-i indekslərinə görə toplayırıq.
# Hər iki Series-də eyni indeks varsa dəyərlər toplanır.
# Yalnız bir Series-də olan indekslər üçün nəticə `NaN` ola bilər.
sales_q1 + sales_q2

Brazil      NaN
China     950.0
India     202.0
Japan       NaN
USA       510.0
dtype: float64

In [108]:
# `.add()` iki Series-i indekslərinə görə toplayır.
# `fill_value=0` — bir Series-də olmayan indeks üçün çatışmayan dəyəri 0 qəbul edir.
first_half = sales_q1.add(sales_q2, fill_value=0)

# Alınmış nəticəni göstəririk.
first_half

Brazil    100.0
China     950.0
India     202.0
Japan      80.0
USA       510.0
dtype: float64

In [109]:
# DataFrame üçün sütun adlarını siyahı şəklində yaradırıq.
my_columns = ["Jan", "Feb", "Mart"]

In [110]:
# `np.random.seed(42)` təsadüfi ədədlərin hər dəfə eyni ardıcıllıqla yaranmasını təmin edir.
np.random.seed(42)

# `np.random.randint(0, 101, (4, 3))`
# 0-dan 100-ə qədər təsadüfi tam ədədlərdən 4 sətir və 3 sütunlu massiv yaradır.
my_data = np.random.randint(0, 101, (4, 3))

# Yaradılmış NumPy massivini göstəririk.
my_data

array([[51, 92, 14],
       [71, 60, 20],
       [82, 86, 74],
       [74, 87, 99]], dtype=int32)

In [111]:
# `pd.DataFrame()` ikiölçülü cədvəl yaradır.
# `data=my_data` — cədvəldəki məlumatlardır.
# `columns=my_columns` — sütun adlarıdır.
# `index=my_index` — sətir indeksləridir.
df = pd.DataFrame(data=my_data, columns=my_columns, index=my_index)

In [112]:
# DataFrame-i ekrana çıxarırıq.
df

            Jan  Feb  Mart
USA          51   92    14
Canada       71   60    20
Mexico       82   86    74
Azerbaijan   74   87    99

In [113]:
# `.info()` DataFrame haqqında ümumi məlumat göstərir:
# sətir sayı, sütunlar, boş olmayan dəyərlərin sayı, data type və yaddaş istifadəsi.
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, USA to Azerbaijan
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int32
 1   Feb     4 non-null      int32
 2   Mart    4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes

In [114]:
# `pd.read_csv()` CSV faylındakı məlumatları oxuyaraq DataFrame yaradır.
employee_data_frame = pd.read_csv("data/employees.csv")

# Yüklənmiş DataFrame-i göstəririk.
employee_data_frame

     ID      Name   Age     Country  Salary  ExperienceYears Remote Department
0     1      Lucy  56.0         USA   30854             15.0    Yes         IT
1     2  Victoria  46.0  Azerbaijan   68623             11.0    Yes         HR
2     3  Benjamin  32.0     Germany   37392             18.0     No  Marketing
3     4      Luna  25.0         USA   85680              NaN     No    Finance
4     5       Zoe  38.0      Brazil   76717              5.0    Yes     Design
..  ...       ...   ...         ...     ...              ...    ...        ...
95   96   Abigail  59.0         USA   52399             16.0    Yes    Finance
96   97    Harper  56.0         USA   76214              NaN    Yes         IT
97   98      Owen  58.0      France  116416              4.0     No     Design
98   99     Ethan  45.0         USA  100271              8.0    Yes     Design
99  100   Grayson  24.0     Germany   74064             11.0    Yes         HR

[100 rows x 8 columns]

In [115]:
# `.columns` DataFrame-də olan bütün sütun adlarını qaytarır.
employee_data_frame.columns

Index(['ID', 'Name', 'Age', 'Country', 'Salary', 'ExperienceYears', 'Remote',
       'Department'],
      dtype='str')

In [116]:
# `.info()` DataFrame-in strukturu və sütun tipləri haqqında məlumat göstərir.
employee_data_frame.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               100 non-null    int64
 1   Name             100 non-null    str
 2   Age              99 non-null     float64
 3   Country          100 non-null    str
 4   Salary           100 non-null    int64
 5   ExperienceYears  98 non-null     float64
 6   Remote           100 non-null    str
 7   Department       100 non-null    str
dtypes: float64(2), int64(2), str(4)
memory usage: 6.4 KB

In [117]:
# `.head()` ilk 5 sətri göstərir.
employee_data_frame.head()

   ID      Name   Age     Country  Salary  ExperienceYears Remote Department
0   1      Lucy  56.0         USA   30854             15.0    Yes         IT
1   2  Victoria  46.0  Azerbaijan   68623             11.0    Yes         HR
2   3  Benjamin  32.0     Germany   37392             18.0     No  Marketing
3   4      Luna  25.0         USA   85680              NaN     No    Finance
4   5       Zoe  38.0      Brazil   76717              5.0    Yes     Design

In [118]:
# `.head(13)` ilk 13 sətri göstərir.
employee_data_frame.head(13)

    ID       Name   Age     Country  Salary  ExperienceYears Remote Department
0    1       Lucy  56.0         USA   30854             15.0    Yes         IT
1    2   Victoria  46.0  Azerbaijan   68623             11.0    Yes         HR
2    3   Benjamin  32.0     Germany   37392             18.0     No  Marketing
3    4       Luna  25.0         USA   85680              NaN     No    Finance
4    5        Zoe  38.0      Brazil   76717              5.0    Yes     Design
5    6  Sebastian  56.0       Japan  117092              5.0    Yes     Design
6    7    Paisley  36.0      France   80859             12.0     No    Finance
7    8      Jaxon  40.0  Azerbaijan   56309             18.0     No         HR
8    9      Aiden  28.0      Brazil  117455              7.0     No     Design
9   10      Wyatt  28.0      France   93734              1.0     No  Marketing
10  11      Logan  41.0      France  100467              0.0     No         HR
11  12      Riley  53.0         USA   82662             14.0    Yes  Marketing
12  13     Elijah  57.0      France   42688              0.0     No         IT

In [119]:
# `.tail()` son 5 sətri göstərir.
employee_data_frame.tail()

     ID     Name   Age  Country  Salary  ExperienceYears Remote Department
95   96  Abigail  59.0      USA   52399             16.0    Yes    Finance
96   97   Harper  56.0      USA   76214              NaN    Yes         IT
97   98     Owen  58.0   France  116416              4.0     No     Design
98   99    Ethan  45.0      USA  100271              8.0    Yes     Design
99  100  Grayson  24.0  Germany   74064             11.0    Yes         HR

In [120]:
# `.tail(10)` son 10 sətri göstərir.
employee_data_frame.tail(10)

     ID      Name   Age  Country  Salary  ExperienceYears Remote Department
90   91    Skylar   NaN   Brazil   68467             15.0     No         HR
91   92      John  52.0  Germany   53328             12.0    Yes    Finance
92   93    Samuel  52.0   France  116831             17.0    Yes         IT
93   94      Nora  50.0      USA   33987              9.0    Yes         HR
94   95  Penelope  22.0    Japan   88871             18.0    Yes         HR
95   96   Abigail  59.0      USA   52399             16.0    Yes    Finance
96   97    Harper  56.0      USA   76214              NaN    Yes         IT
97   98      Owen  58.0   France  116416              4.0     No     Design
98   99     Ethan  45.0      USA  100271              8.0    Yes     Design
99  100   Grayson  24.0  Germany   74064             11.0    Yes         HR

In [121]:
# `.sample(6)` DataFrame-dən təsadüfi 6 sətir seçir.
employee_data_frame.sample(6)

    ID     Name   Age Country  Salary  ExperienceYears Remote Department
81  82   Sophia  42.0  Brazil  112018              6.0     No     Design
4    5      Zoe  38.0  Brazil   76717              5.0    Yes     Design
40  41     Liam  31.0  Brazil  118614              1.0     No    Finance
69  70  Jackson  40.0     USA   36295             16.0     No     Design
10  11    Logan  41.0  France  100467              0.0     No         HR
45  46      Zoé  45.0  Brazil  103656              0.0     No         IT

In [122]:
# `.describe()` ədədi sütunlar üçün əsas statistik göstəriciləri hesablayır:
# count, mean, std, min, 25%, 50%, 75% və max.
employee_data_frame.describe()

               ID        Age        Salary  ExperienceYears
count  100.000000  99.000000     100.00000        98.000000
mean    50.500000  38.040404   72947.80000         9.438776
std     29.011492  12.211503   27241.56386         6.066753
min      1.000000  18.000000   30854.00000         0.000000
25%     25.750000  27.500000   49860.50000         4.000000
50%     50.500000  38.000000   73540.00000         9.500000
75%     75.250000  46.500000   95972.25000        15.000000
max    100.000000  59.000000  119045.00000        19.000000

# Pandas `describe()` statistik göstəriciləri

## `describe()`

`describe()` — `DataFrame` və ya `Series` daxilində ədədi məlumatların əsas statistik göstəricilərini göstərir.

```python
df.describe()
```

Nəticədə aşağıdakı göstəricilər alınır:

---

## `count`

**count** — boş olmayan dəyərlərin sayını göstərir.

`NaN` olan dəyərlər sayılmır.

Məsələn, sütunda 100 sətir varsa, amma 5 dəyər boşdursa:

```text
count = 95
```

Bu göstərici məlumatlarda çatışmayan dəyərlərin olub-olmadığını anlamağa kömək edir.

---

## `mean`

**mean** — ədədlərin orta qiymətidir.

Bütün qiymətlər toplanır və onların sayına bölünür.

Formula:

```text
mean = dəyərlərin cəmi / dəyərlərin sayı
```

Məsələn:

```text
10, 20, 30
```

```text
mean = (10 + 20 + 30) / 3 = 20
```

Orta qiymət məlumatların ümumi səviyyəsini göstərmək üçün istifadə olunur.

---

## `std`

**std** — standart kənarlaşmadır.

Dəyərlərin orta qiymətdən nə qədər uzaqda yerləşdiyini göstərir.

- `std` kiçikdirsə — dəyərlər bir-birinə və orta qiymətə yaxındır.
- `std` böyükdürsə — dəyərlər daha çox səpələnib.

Məsələn:

```text
10, 11, 12
```

Bu qiymətlər bir-birinə yaxın olduğu üçün standart kənarlaşma kiçik olacaq.

Amma:

```text
1, 50, 100
```

qiymətləri bir-birindən çox fərqləndiyi üçün standart kənarlaşma böyük olacaq.

---

## `min`

**min** — məlumatlardakı minimum, yəni ən kiçik qiyməti göstərir.

Məsələn:

```text
10, 20, 30, 5
```

Nəticə:

```text
min = 5
```

---

## `25%`

**25%** — birinci kvartildir və `Q1` kimi də işarə olunur.

Məlumatların təxminən `25%`-i bu qiymətdən kiçik və ya ona bərabər olur.

Məsələn:

```text
25% = 20
```

Bu o deməkdir ki, məlumatların təxminən dörddə biri `20` və ya daha aşağı qiymətlərdən ibarətdir.

---

## `50%`

**50%** — median və ya ikinci kvartildir (`Q2`).

Məlumatları kiçikdən böyüyə düzdükdə ortada yerləşən qiyməti göstərir.

Məlumatların:

- `50%`-i mediandan aşağı,
- `50%`-i mediandan yuxarı olur.

Məsələn:

```text
10, 20, 30, 40, 50
```

Burada:

```text
median = 30
```

Median çox böyük və ya çox kiçik ekstremal qiymətlər olduqda orta qiymətdən daha faydalı ola bilər.

---

## `75%`

**75%** — üçüncü kvartildir və `Q3` kimi işarə olunur.

Məlumatların təxminən `75%`-i bu qiymətdən kiçik və ya ona bərabər olur.

Başqa sözlə, məlumatların yalnız təxminən `25%`-i bu qiymətdən böyük olur.

Məsələn:

```text
75% = 80
```

Bu o deməkdir ki, məlumatların təxminən `75%`-i `80` və ya daha aşağıdır.

---

## `max`

**max** — məlumatlardakı maksimum, yəni ən böyük qiyməti göstərir.

Məsələn:

```text
10, 20, 30, 50
```

Nəticə:

```text
max = 50
```

---

## Qısa nümunə

Əgər qiymətlər belədirsə:

```text
10, 20, 30, 40, 50
```

`describe()` nəticəsi bizə bu məlumatları verə bilər:

| Göstərici | Mənası |
|---|---|
| `count` | Dəyərlərin sayı |
| `mean` | Orta qiymət |
| `std` | Standart kənarlaşma |
| `min` | Ən kiçik qiymət |
| `25%` | Birinci kvartil (`Q1`) |
| `50%` | Median (`Q2`) |
| `75%` | Üçüncü kvartil (`Q3`) |
| `max` | Ən böyük qiymət |

## Pandas nümunəsi

```python
import pandas as pd

data = {
    "qiymet": [10, 20, 30, 40, 50]
}

df = pd.DataFrame(data)

df.describe()
```

Bu kod `qiymet` sütunu üçün əsas statistik göstəriciləri hesablayacaq.

In [123]:
# `"Age"` sütununu seçirik və `.mean()` ilə orta yaşı hesablayırıq.
employee_data_frame["Age"].mean()

np.float64(38.04040404040404)

In [124]:
# `"Age"` sütununda `.max()` ilə ən böyük yaşı tapırıq.
employee_data_frame["Age"].max()

np.float64(59.0)

In [125]:
# `"Age"` sütununda `.min()` ilə ən kiçik yaşı tapırıq.
employee_data_frame["Age"].min()

np.float64(18.0)

In [126]:
# `employee_data_frame['Age'] > 50` hər sətir üçün True/False şərti yaradır.
# DataFrame daxilində bu şərtdən istifadə edərək yaşı 50-dən böyük olan sətirləri filtr edirik.
employee_data_frame[employee_data_frame['Age'] > 50]

    ID       Name   Age     Country  Salary  ExperienceYears Remote Department
0    1       Lucy  56.0         USA   30854             15.0    Yes         IT
5    6  Sebastian  56.0       Japan  117092              5.0    Yes     Design
11  12      Riley  53.0         USA   82662             14.0    Yes  Marketing
12  13     Elijah  57.0      France   42688              0.0     No         IT
19  20     Evelyn  55.0      Brazil   64698             16.0     No  Marketing
27  28     Thomas  59.0         USA   79811             13.0     No     Design
32  33    Eleanor  54.0       Japan   41411              2.0    Yes         IT
36  37       Leah  56.0  Azerbaijan   38680              7.0    Yes         IT
48  49       Noah  52.0      Brazil   51918             15.0     No  Marketing
51  52       Ezra  53.0  Azerbaijan   60306              2.0     No         IT
52  53      Dylan  57.0  Azerbaijan   46646             17.0    Yes    Finance
56  57    Lillian  59.0      France   32049             12.0    Yes  Marketing
61  62   Isabella  51.0         USA  102694             15.0     No         IT
63  64      James  53.0         USA   37400             11.0     No    Finance
70  71       Lily  57.0      France   89040             19.0    Yes     Design
77  78       Ryan  58.0      France   91267              7.0     No    Finance
91  92       John  52.0     Germany   53328             12.0    Yes    Finance
92  93     Samuel  52.0      France  116831             17.0    Yes         IT
95  96    Abigail  59.0         USA   52399             16.0    Yes    Finance
96  97     Harper  56.0         USA   76214              NaN    Yes         IT
97  98       Owen  58.0      France  116416              4.0     No     Design

In [127]:
# `.value_counts()` `"Age"` sütunundakı hər unikal yaşın neçə dəfə təkrarlandığını göstərir.
employee_data_frame["Age"].value_counts()

Age
41.0    6
56.0    4
32.0    4
25.0    4
38.0    4
19.0    4
42.0    4
24.0    4
31.0    4
46.0    3
28.0    3
53.0    3
57.0    3
59.0    3
45.0    3
26.0    3
35.0    3
21.0    3
43.0    3
52.0    3
40.0    2
20.0    2
39.0    2
50.0    2
33.0    2
34.0    2
58.0    2
18.0    2
36.0    1
47.0    1
55.0    1
29.0    1
44.0    1
54.0    1
37.0    1
23.0    1
51.0    1
27.0    1
48.0    1
22.0    1
Name: count, dtype: int64

In [128]:
# `.value_counts()` `"Country"` sütunundakı hər ölkənin neçə dəfə təkrarlandığını göstərir.
employee_data_frame["Country"].value_counts()

Country
USA           22
Azerbaijan    18
France        18
Brazil        17
Japan         14
Germany       11
Name: count, dtype: int64

In [129]:
# `.groupby("Country")` sətirləri ölkəyə görə qruplaşdırır.
# `["Salary"]` hər qrupdan Salary sütununu seçir.
# `.mean()` isə hər ölkə üzrə orta maaşı hesablayır.
employee_data_frame.groupby("Country")["Salary"].mean()

Country
Azerbaijan    72012.555556
Brazil        76001.882353
France        85016.111111
Germany       62115.000000
Japan         72384.214286
USA           67254.000000
Name: Salary, dtype: float64

employee_data_frame.groupby("Country")["Salary"].mean()

SELECT Country, AVG(Age)

FROM Employees

GROUP BY Country

In [130]:
# `.index` DataFrame-in mövcud sətir indekslərini qaytarır.
employee_data_frame.index

RangeIndex(start=0, stop=100, step=1)

In [131]:
# `.describe()` əsas statistik göstəriciləri hesablayır.
# `.transpose()` sətir və sütunların yerini dəyişir ki, nəticə daha rahat oxunsun.
employee_data_frame.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
ID,100.0,50.500000,29.011492,1.0,25.75,50.5,75.25,100.0
Age,99.0,38.040404,12.211503,18.0,27.50,38.0,46.50,59.0
Salary,100.0,72947.800000,27241.563860,30854.0,49860.50,73540.0,95972.25,119045.0
ExperienceYears,98.0,9.438776,6.066753,0.0,4.00,9.5,15.00,19.0

In [132]:
# Tək kvadrat mötərizə ilə `"Country"` sütununu Series kimi seçirik.
employee_data_frame["Country"]

0            USA
1     Azerbaijan
2        Germany
3            USA
4         Brazil
         ...
95           USA
96           USA
97        France
98           USA
99       Germany
Name: Country, Length: 100, dtype: str

In [133]:
# İkiqat kvadrat mötərizə ilə `"Country"` və `"Name"` sütunlarını DataFrame kimi seçirik.
employee_data_frame[["Country", "Name"]]

       Country      Name
0          USA      Lucy
1   Azerbaijan  Victoria
2      Germany  Benjamin
3          USA      Luna
4       Brazil       Zoe
..         ...       ...
95         USA   Abigail
96         USA    Harper
97      France      Owen
98         USA     Ethan
99     Germany   Grayson

[100 rows x 2 columns]

In [134]:
# `.drop("Country", axis=1)` `"Country"` sütununu silinmiş formada yeni nəticə qaytarır.
# `axis=1` əməliyyatın sütun üzərində aparıldığını bildirir.
# `inplace=True` olmadığı üçün əsas DataFrame dəyişmir.
employee_data_frame.drop("Country", axis=1)

     ID      Name   Age  Salary  ExperienceYears Remote Department
0     1      Lucy  56.0   30854             15.0    Yes         IT
1     2  Victoria  46.0   68623             11.0    Yes         HR
2     3  Benjamin  32.0   37392             18.0     No  Marketing
3     4      Luna  25.0   85680              NaN     No    Finance
4     5       Zoe  38.0   76717              5.0    Yes     Design
..  ...       ...   ...     ...              ...    ...        ...
95   96   Abigail  59.0   52399             16.0    Yes    Finance
96   97    Harper  56.0   76214              NaN    Yes         IT
97   98      Owen  58.0  116416              4.0     No     Design
98   99     Ethan  45.0  100271              8.0    Yes     Design
99  100   Grayson  24.0   74064             11.0    Yes         HR

[100 rows x 7 columns]

In [135]:
# Əsas DataFrame-i göstəririk.
# Əvvəlki `drop()` inplace olmadığı üçün `"Country"` sütunu hələ də mövcuddur.
employee_data_frame

     ID      Name   Age     Country  Salary  ExperienceYears Remote Department
0     1      Lucy  56.0         USA   30854             15.0    Yes         IT
1     2  Victoria  46.0  Azerbaijan   68623             11.0    Yes         HR
2     3  Benjamin  32.0     Germany   37392             18.0     No  Marketing
3     4      Luna  25.0         USA   85680              NaN     No    Finance
4     5       Zoe  38.0      Brazil   76717              5.0    Yes     Design
..  ...       ...   ...         ...     ...              ...    ...        ...
95   96   Abigail  59.0         USA   52399             16.0    Yes    Finance
96   97    Harper  56.0         USA   76214              NaN    Yes         IT
97   98      Owen  58.0      France  116416              4.0     No     Design
98   99     Ethan  45.0         USA  100271              8.0    Yes     Design
99  100   Grayson  24.0     Germany   74064             11.0    Yes         HR

[100 rows x 8 columns]

In [136]:
# `.drop()` `"Country"` sütununu silir.
# `axis=1` — sütunu silirik.
# `inplace=True` — dəyişiklik birbaşa mövcud DataFrame-də edilir.
employee_data_frame.drop("Country", axis=1, inplace=True)

In [137]:
# Dəyişdirilmiş DataFrame-i göstəririk.
employee_data_frame

     ID      Name   Age  Salary  ExperienceYears Remote Department
0     1      Lucy  56.0   30854             15.0    Yes         IT
1     2  Victoria  46.0   68623             11.0    Yes         HR
2     3  Benjamin  32.0   37392             18.0     No  Marketing
3     4      Luna  25.0   85680              NaN     No    Finance
4     5       Zoe  38.0   76717              5.0    Yes     Design
..  ...       ...   ...     ...              ...    ...        ...
95   96   Abigail  59.0   52399             16.0    Yes    Finance
96   97    Harper  56.0   76214              NaN    Yes         IT
97   98      Owen  58.0  116416              4.0     No     Design
98   99     Ethan  45.0  100271              8.0    Yes     Design
99  100   Grayson  24.0   74064             11.0    Yes         HR

[100 rows x 7 columns]

In [138]:
# `.drop(0, axis=0)` indeks dəyəri 0 olan sətri silir.
# `axis=0` — əməliyyatın sətir üzərində aparıldığını bildirir.
# `inplace=True` — dəyişiklik birbaşa DataFrame-də edilir.
employee_data_frame.drop(0, axis=0, inplace=True)

In [139]:
# Sətir silindikdən sonra DataFrame-i göstəririk.
employee_data_frame

     ID       Name   Age  Salary  ExperienceYears Remote Department
1     2   Victoria  46.0   68623             11.0    Yes         HR
2     3   Benjamin  32.0   37392             18.0     No  Marketing
3     4       Luna  25.0   85680              NaN     No    Finance
4     5        Zoe  38.0   76717              5.0    Yes     Design
5     6  Sebastian  56.0  117092              5.0    Yes     Design
..  ...        ...   ...     ...              ...    ...        ...
95   96    Abigail  59.0   52399             16.0    Yes    Finance
96   97     Harper  56.0   76214              NaN    Yes         IT
97   98       Owen  58.0  116416              4.0     No     Design
98   99      Ethan  45.0  100271              8.0    Yes     Design
99  100    Grayson  24.0   74064             11.0    Yes         HR

[99 rows x 7 columns]

In [140]:
# `.shape` DataFrame-in ölçüsünü `(sətir_sayı, sütun_sayı)` formasında qaytarır.
employee_data_frame.shape

(99, 7)

In [141]:
# `.set_index("Name")` `"Name"` sütununu DataFrame-in yeni indeksi edir.
# `inplace=True` dəyişiklikləri birbaşa DataFrame-də saxlayır.
employee_data_frame.set_index("Name", inplace=True)

In [142]:
# Yeni indeks tətbiq edildikdən sonra DataFrame-i göstəririk.
employee_data_frame

            ID   Age  Salary  ExperienceYears Remote Department
Name
Victoria     2  46.0   68623             11.0    Yes         HR
Benjamin     3  32.0   37392             18.0     No  Marketing
Luna         4  25.0   85680              NaN     No    Finance
Zoe          5  38.0   76717              5.0    Yes     Design
Sebastian    6  56.0  117092              5.0    Yes     Design
...        ...   ...     ...              ...    ...        ...
Abigail     96  59.0   52399             16.0    Yes    Finance
Harper      97  56.0   76214              NaN    Yes         IT
Owen        98  58.0  116416              4.0     No     Design
Ethan       99  45.0  100271              8.0    Yes     Design
Grayson    100  24.0   74064             11.0    Yes         HR

[99 rows x 6 columns]

In [143]:
# `.loc["Zoe"]` indeks etiketinə görə `"Zoe"` adlı sətri seçir.
employee_data_frame.loc["Zoe"]

ID                      5
Age                  38.0
Salary              76717
ExperienceYears       5.0
Remote                Yes
Department         Design
Name: Zoe, dtype: object

In [144]:
# `.iloc[4]` sətirin mövqeyinə görə 5-ci sətri seçir.
# `iloc` 0-dan başlayan rəqəmsal mövqedən istifadə edir.
employee_data_frame.iloc[4]

ID                      6
Age                  56.0
Salary             117092
ExperienceYears       5.0
Remote                Yes
Department         Design
Name: Sebastian, dtype: object

In [145]:
# `.dtypes` hər sütunun məlumat tipini göstərir.
employee_data_frame.dtypes

ID                   int64
Age                float64
Salary               int64
ExperienceYears    float64
Remote                 str
Department             str
dtype: object

In [146]:
# `"Department"` sütununu seçirik.
# `.str` mətn metodlarından istifadə etməyə imkan verir.
# `.lower()` bütün mətnləri kiçik hərflərə çevirir.
employee_data_frame['Department'].str.lower()

Name
Victoria            hr
Benjamin     marketing
Luna           finance
Zoe             design
Sebastian       design
               ...
Abigail        finance
Harper              it
Owen            design
Ethan           design
Grayson             hr
Name: Department, Length: 99, dtype: str

In [147]:
# `.str.contains("Design")` hər dəyərdə `"Design"` sözünün olub-olmadığını yoxlayır.
# Nəticədə hər sətir üçün `True` və ya `False` qaytarılır.
employee_data_frame['Department'].str.contains("Design")

Name
Victoria     False
Benjamin     False
Luna         False
Zoe           True
Sebastian     True
             ...
Abigail      False
Harper       False
Owen          True
Ethan         True
Grayson      False
Name: Department, Length: 99, dtype: bool

In [148]:
# `+= 1` `"Age"` sütunundakı hər yaş dəyərinə 1 əlavə edir.
# Bu əməliyyat DataFrame-i birbaşa dəyişir.
employee_data_frame['Age'] += 1

# Dəyişdirilmiş DataFrame-i göstəririk.
employee_data_frame

            ID   Age  Salary  ExperienceYears Remote Department
Name
Victoria     2  47.0   68623             11.0    Yes         HR
Benjamin     3  33.0   37392             18.0     No  Marketing
Luna         4  26.0   85680              NaN     No    Finance
Zoe          5  39.0   76717              5.0    Yes     Design
Sebastian    6  57.0  117092              5.0    Yes     Design
...        ...   ...     ...              ...    ...        ...
Abigail     96  60.0   52399             16.0    Yes    Finance
Harper      97  57.0   76214              NaN    Yes         IT
Owen        98  59.0  116416              4.0     No     Design
Ethan       99  46.0  100271              8.0    Yes     Design
Grayson    100  25.0   74064             11.0    Yes         HR

[99 rows x 6 columns]

In [149]:
# `.rename()` sütun adlarını dəyişmək üçün istifadə olunur.
# `columns={"Salary": "Maaş"}` — `"Salary"` sütununun adını `"Maaş"` edir.
# `inplace=True` — dəyişiklik birbaşa DataFrame-də saxlanılır.
employee_data_frame.rename(columns={"Salary": "Maaş"}, inplace=True)

In [150]:
# Sütun adı dəyişdirildikdən sonra DataFrame-i göstəririk.
employee_data_frame

            ID   Age    Maaş  ExperienceYears Remote Department
Name
Victoria     2  47.0   68623             11.0    Yes         HR
Benjamin     3  33.0   37392             18.0     No  Marketing
Luna         4  26.0   85680              NaN     No    Finance
Zoe          5  39.0   76717              5.0    Yes     Design
Sebastian    6  57.0  117092              5.0    Yes     Design
...        ...   ...     ...              ...    ...        ...
Abigail     96  60.0   52399             16.0    Yes    Finance
Harper      97  57.0   76214              NaN    Yes         IT
Owen        98  59.0  116416              4.0     No     Design
Ethan       99  46.0  100271              8.0    Yes     Design
Grayson    100  25.0   74064             11.0    Yes         HR

[99 rows x 6 columns]

In [151]:
# `.sort_values(by="Age")` sətirləri `"Age"` sütununa görə artan sıra ilə sıralayır.
employee_data_frame.sort_values(by="Age")

          ID   Age    Maaş  ExperienceYears Remote Department
Name
Leo       86  19.0   51357             19.0     No     Design
Ava       81  19.0   68360              4.0    Yes     Design
Scarlett  17  20.0   82083              3.0     No         HR
Olivia    21  20.0  110623             11.0    Yes         IT
Julian    55  20.0   46371              6.0     No     Design
...       ..   ...     ...              ...    ...        ...
Owen      98  59.0  116416              4.0     No     Design
Thomas    28  60.0   79811             13.0     No     Design
Lillian   57  60.0   32049             12.0    Yes  Marketing
Abigail   96  60.0   52399             16.0    Yes    Finance
Skylar    91   NaN   68467             15.0     No         HR

[99 rows x 6 columns]

In [152]:
# `.sort_values(by="Age", ascending=False)` sətirləri yaşa görə azalan sıra ilə sıralayır.
# `ascending=False` — böyükdən kiçiyə sıralama deməkdir.
employee_data_frame.sort_values(by="Age", ascending=False)

         ID   Age    Maaş  ExperienceYears Remote Department
Name
Thomas   28  60.0   79811             13.0     No     Design
Lillian  57  60.0   32049             12.0    Yes  Marketing
Abigail  96  60.0   52399             16.0    Yes    Finance
Ryan     78  59.0   91267              7.0     No    Finance
Owen     98  59.0  116416              4.0     No     Design
...      ..   ...     ...              ...    ...        ...
Julian   55  20.0   46371              6.0     No     Design
Charles  44  20.0   31802             16.0    Yes     Design
Ava      81  19.0   68360              4.0    Yes     Design
Leo      86  19.0   51357             19.0     No     Design
Skylar   91   NaN   68467             15.0     No         HR

[99 rows x 6 columns]

In [153]:
# `.isna()` hər xanada boş (`NaN`) dəyər olub-olmadığını True/False ilə göstərir.
# `.sum()` hər sütunda neçə `True`, yəni neçə boş dəyər olduğunu sayır.
employee_data_frame.isna().sum()

ID                 0
Age                1
Maaş               0
ExperienceYears    2
Remote             0
Department         0
dtype: int64

In [154]:
# `.dropna()` ən azı bir boş (`NaN`) dəyəri olan sətirləri nəticədən çıxarır.
# `inplace=True` olmadığı üçün əsas DataFrame dəyişmir.
employee_data_frame.dropna()

            ID   Age    Maaş  ExperienceYears Remote Department
Name
Victoria     2  47.0   68623             11.0    Yes         HR
Benjamin     3  33.0   37392             18.0     No  Marketing
Zoe          5  39.0   76717              5.0    Yes     Design
Sebastian    6  57.0  117092              5.0    Yes     Design
Paisley      7  37.0   80859             12.0     No    Finance
...        ...   ...     ...              ...    ...        ...
Penelope    95  23.0   88871             18.0    Yes         HR
Abigail     96  60.0   52399             16.0    Yes    Finance
Owen        98  59.0  116416              4.0     No     Design
Ethan       99  46.0  100271              8.0    Yes     Design
Grayson    100  25.0   74064             11.0    Yes         HR

[96 rows x 6 columns]

In [155]:
# `.fillna(0)` bütün boş (`NaN`) dəyərləri 0 ilə əvəz edən yeni nəticə qaytarır.
# `inplace=True` olmadığı üçün əsas DataFrame dəyişmir.
employee_data_frame.fillna(0)

            ID   Age    Maaş  ExperienceYears Remote Department
Name
Victoria     2  47.0   68623             11.0    Yes         HR
Benjamin     3  33.0   37392             18.0     No  Marketing
Luna         4  26.0   85680              0.0     No    Finance
Zoe          5  39.0   76717              5.0    Yes     Design
Sebastian    6  57.0  117092              5.0    Yes     Design
...        ...   ...     ...              ...    ...        ...
Abigail     96  60.0   52399             16.0    Yes    Finance
Harper      97  57.0   76214              0.0    Yes         IT
Owen        98  59.0  116416              4.0     No     Design
Ethan       99  46.0  100271              8.0    Yes     Design
Grayson    100  25.0   74064             11.0    Yes         HR

[99 rows x 6 columns]

In [156]:
# `employee_data_frame['Age'].mean()` yaş sütununun orta qiymətini hesablayır.
# `.fillna(...)` DataFrame-dəki boş dəyərləri verilən orta yaş ilə əvəz edir.
# `inplace=True` dəyişiklikləri birbaşa DataFrame-də saxlayır.
employee_data_frame.fillna(employee_data_frame['Age'].mean(), inplace=True)

            ID   Age    Maaş  ExperienceYears Remote Department
Name
Victoria     2  47.0   68623        11.000000    Yes         HR
Benjamin     3  33.0   37392        18.000000     No  Marketing
Luna         4  26.0   85680        38.857143     No    Finance
Zoe          5  39.0   76717         5.000000    Yes     Design
Sebastian    6  57.0  117092         5.000000    Yes     Design
...        ...   ...     ...              ...    ...        ...
Abigail     96  60.0   52399        16.000000    Yes    Finance
Harper      97  57.0   76214        38.857143    Yes         IT
Owen        98  59.0  116416         4.000000     No     Design
Ethan       99  46.0  100271         8.000000    Yes     Design
Grayson    100  25.0   74064        11.000000    Yes         HR

[99 rows x 6 columns]

In [157]:
# `.loc["Skylar"]` indeks etiketi `"Skylar"` olan sətri seçir.
employee_data_frame.loc["Skylar"]

ID                        91
Age                38.857143
Maaş                   68467
ExperienceYears         15.0
Remote                    No
Department                HR
Name: Skylar, dtype: object

In [158]:
# `.unique()` `"Department"` sütunundakı təkrarlanmayan unikal dəyərləri qaytarır.
employee_data_frame["Department"].unique()

<StringArray>
['HR', 'Marketing', 'Finance', 'Design', 'IT']
Length: 5, dtype: str

In [159]:
# `.nunique()` `"Department"` sütunundakı unikal dəyərlərin sayını qaytarır.
employee_data_frame["Department"].nunique()

5

In [160]:
# `"Department"` sütununu seçirik.
# `.tail(40)` həmin sütunun son 40 dəyərini göstərir.
employee_data_frame["Department"].tail(40)

Name
Hudson          Design
Isabella            IT
Natalie      Marketing
James          Finance
Brooklyn            IT
Adrian         Finance
Anna           Finance
Henry        Marketing
Andrew              HR
Jackson         Design
Lily            Design
Joshua       Marketing
Matthew        Finance
Mia                 IT
Aurora         Finance
Everly       Marketing
Christian       Design
Ryan           Finance
Michael         Design
Willow              IT
Ava             Design
Sophia          Design
Mila                HR
Layla               HR
William             HR
Leo             Design
Savannah     Marketing
Stella          Design
Hannah       Marketing
Addison      Marketing
Skylar              HR
John           Finance
Samuel              IT
Nora                HR
Penelope            HR
Abigail        Finance
Harper              IT
Owen            Design
Ethan           Design
Grayson             HR
Name: Department, dtype: str

In [161]:
# `.set_index("ID")` `"ID"` sütununu DataFrame-in indeksi edir.
# `inplace=True` dəyişiklikləri birbaşa DataFrame-də saxlayır.
employee_data_frame.set_index("ID", inplace=True)

In [162]:
# Yeni indeks tətbiq edildikdən sonra DataFrame-i göstəririk.
employee_data_frame

      Age    Maaş  ExperienceYears Remote Department
ID
2    47.0   68623        11.000000    Yes         HR
3    33.0   37392        18.000000     No  Marketing
4    26.0   85680        38.857143     No    Finance
5    39.0   76717         5.000000    Yes     Design
6    57.0  117092         5.000000    Yes     Design
..    ...     ...              ...    ...        ...
96   60.0   52399        16.000000    Yes    Finance
97   57.0   76214        38.857143    Yes         IT
98   59.0  116416         4.000000     No     Design
99   46.0  100271         8.000000    Yes     Design
100  25.0   74064        11.000000    Yes         HR

[99 rows x 5 columns]

In [163]:
# `.reset_index()` mövcud indeksi yenidən adi sütuna çevirir
# və standart 0, 1, 2, ... indeksini bərpa edir.
# `inplace=True` dəyişiklikləri DataFrame-də saxlayır.
employee_data_frame.reset_index(inplace=True)

In [164]:
# İndeks sıfırlandıqdan sonra DataFrame-i göstəririk.
employee_data_frame

     ID   Age    Maaş  ExperienceYears Remote Department
0     2  47.0   68623        11.000000    Yes         HR
1     3  33.0   37392        18.000000     No  Marketing
2     4  26.0   85680        38.857143     No    Finance
3     5  39.0   76717         5.000000    Yes     Design
4     6  57.0  117092         5.000000    Yes     Design
..  ...   ...     ...              ...    ...        ...
94   96  60.0   52399        16.000000    Yes    Finance
95   97  57.0   76214        38.857143    Yes         IT
96   98  59.0  116416         4.000000     No     Design
97   99  46.0  100271         8.000000    Yes     Design
98  100  25.0   74064        11.000000    Yes         HR

[99 rows x 6 columns]